version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: crafting_cost_calculator
      MARIADB_USER: crafter
      MARIADB_PASSWORD: crafter
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 15s
      timeout: 10s
      retries: 3

  flask-api:
    image: crafting-cost-calculator/flask-api
    build: ./flask-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/item_types"]
      interval: 15s
      timeout: 10s
      retries: 3

  react-app:
    image: crafting-cost-calculator/react-app
    build: ./react-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      flask-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
    
volumes:
  db-data:
