version: "3.1"

services:
  flask-api:
    volumes:
      - /home/eris/dev/crafting-cost-calculator/flask-api:/home/crafter/app
    environment:
      FLASK_DEBUG: 1

  react-app:
    volumes:
      - /home/eris/dev/crafting-cost-calculator/react-app:/home/crafter/app
      
    environment:
      DEBUG: 1
